//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodPaletteApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealPerDay
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int UserID { get; set; }
        public int DishID { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual User User { get; set; }
    }
}
